language: python

python:
    - 2.7
env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==13.2.0 PYOPENSSL=PyOpenSSL

install:
  - pip install $TWISTED
  - sh install.sh
  - 'test -n "$PYOPENSSL" && pip install $PYOPENSSL || true'

script:
  - trial lisa

notifications:
  irc: "irc.oftc.net#lisa"
branches:
  only:
    - master
