language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev build-essential gstreamer0.10-plugins-good

python:
    - 2.7
env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==13.2.0 PYOPENSSL=PyOpenSSL

install:
  - pip install $TWISTED --use-mirrors
  - 'test -n "$PYOPENSSL" && pip install $PYOPENSSL --use-mirrors || true'
  - pip install -r requirements.txt --use-mirrors

script:
  - trial lisa

notifications:
  irc: "irc.oftc.net#lisa"
branches:
  only:
    - master
