language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qy python-dev build-essential gstreamer0.10-plugins-good gstreamer0.10-pocketsphinx gstreamer0.10-alsa

python:
    - 2.7
env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk PYOPENSSL=PyOpenSSL
  - TWISTED=Twisted==13.2.0 PYOPENSSL=PyOpenSSL

install:
  - pip install $TWISTED
  - pip install PyGObject
  - 'test -n "$PYOPENSSL" && pip install $PYOPENSSL || true'
  - pip install -r requirements.txt

script:
  - trial lisa

notifications:
  irc: "irc.oftc.net#lisa"
branches:
  only:
    - master
